name: Get Top Reply
description: Fetches the reply with the most likes and its image, for the latest story tweet.
inputs:
  twitter-account-id:
    description: The account ID of the magic frog.
    required: true
  twitter-bearer-token:
    description: The bearer token for the frosg's twitter account.
    required: true
outputs:
  story-number:
    description: The number of the current story.
  reply-id:
    description: The ID of the top reply
  username:
    description: The author of the top reply
  text:
    description: The text of the top reply
  text-clean:
    description: The text of the top reply, cleaned up for audio conversion
  image:
    description: The image of the top reply
runs:
  using: node12
  main: ./index.js
