name: Sponsors
description: Reads transactions to frog's address and adds sponsors.
inputs:
  etherscan-api-url:
    description: Etherscan API url
    required: true
  etherscan-api-key:
    description: Etherscan API key
    required: true
  twitter-consumer-key:
    description: The consumer key frog's twitter account.
    required: true
  twitter-consumer-secret:
    description: The consumer secret for the frog's twitter account.
    required: true
  twitter-access-token-key:
    description: The access token key for the frog's twitter account.
    required: true
  twitter-access-token-secret:
    description: The access token secret for the frog's twitter account.
    required: true
outputs:
  changed:
    description: Whether new sponsors have been added.
runs:
  using: node12
  main: ./index.js
