# This workflow is only to generate audio manually.
# The audio for stories is generated in magic-story-machine workflow.
name: Generate Audio
on:
  workflow_dispatch:

env:
  VOICE: en-GB-Wavenet-F
  PITCH: 7

jobs:
  generate-audio:
    name: Generate Audio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo
      
      # Set up Google Cloud for Text to Speech
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@0aa92bcd70fc0929f052b47276d5e61f793c384b
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
        
      # Convert text configured in secrets to audio
      - name: Convert Text To Audio
        run: |
          # Use Google text to speech
          export TEXT=$(cat repo/generated-audio.txt)
          curl -X POST \
          -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) \
          -H "Content-Type: application/json; charset=utf-8" \
          -d '{"input":{"ssml":"<speak>'"$TEXT"'</speak>"},"voice":{"languageCode":"en-GB","name":"${{ env.VOICE }}"},"audioConfig":{"audioEncoding":"MP3","pitch": ${{ env.PITCH }}}}' \
          https://texttospeech.googleapis.com/v1/text:synthesize | jq -r '.audioContent' | base64 -d >> repo/generated-audio.mp3
      
      # Update Repo
      - name: Update Repo
        run: |
          cd repo
          
          # Commit and push new files
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "generated audio"
          git push
        