name: The Magic Story Machine
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/magic-story-machine
        with:
          twitter-bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}