name: The Magic Story Machine
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  top-reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/top-reply
        with:
          account-id: ${{ secrets.ACCOUNT_ID }}
          tweet-id: 
          twitter-bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}