name: The Magic Story Machine
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  read:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/magic-story-machine.yml
        with:
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}