name: Add New Sponsors
on:
  schedule:
    # Run once per hours at minute 42.
    # Advice from GitHub: Don't always use times that everybody uses (like 0 * * * *) if not necessary.
    - cron: 42 * * * *
  workflow_dispatch:

jobs:
  sponsors:
    name: Add New Sponsors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: npm ci
      
      - name: Update sponsors and tweet
        uses: ./.github/actions/sponsors
        id: sponsors
        with:
          eth-address: ${{ secrets.ETH_ADDRESS }}
          sponsors-file: ./sponsors.json
          etherscan-api-url: ${{ secrets.ETHERSCAN_API_URL }}
          etherscan-api-key: ${{ secrets.ETHERSCAN_API_KEY }}
          twitter-consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitter-access-token-key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      
      - name: Update Repo and Website
        if: ${{ steps.sponsors.outputs.changed == 'true' }}
        run: |
          # Commit and push new files
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Updated sponsors."
          git push

          # Deploy GitHub Page
          npm ci
          npm run generate
          npm run deploy
        