name: Add New Sponsors
on:
  schedule:
    # Run once per hours at minute 42.
    # Advice from GitHub: Don't always use times that everybody uses (like 0 * * * *) if not necessary.
    - cron: 42 * * * *
  workflow_dispatch:

jobs:
  sponsors:
    name: Add New Sponsors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch new sponsors
        id: fetch-sponsors
        uses: ./.github/actions/sponsors
        with:
          etherscan-api-url: ${{ secrets.ETHERSCAN_API_URL }}
          etherscan-api-key: ${{ secrets.ETHERSCAN_API_KEY }}
      
      - name: Write new sponsors to file
        if: steps.fetch-sponsors.outputs.changed
        run: |
          cat <<EOT > ./content/sponsors.json
          ${{ steps.fetch-sponsors.outputs.json }}
          EOT
      
      - name: Update Repo and Website
        run: |
          if ! git diff-index --quiet HEAD --
          then
            # Commit and push new files
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add .
            git commit -m "Updated sponsors."
            git push

            # Deploy GitHub Page
            npm ci
            npm run generate
            npm run deploy
          fi
        