name: Story Text To Speech
on:
  workflow_dispatch:

jobs:
  text-to-speech:
    name: Text To Speech
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@0aa92bcd70fc0929f052b47276d5e61f793c384b
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Use gcloud CLI
        run: gcloud info